name: Docker Action

on:
  workflow_dispatch:

#  schedule:
 #  - cron: "*/15 * * * *"

jobs:
  Build:
    runs-on: ubuntu-latest
#    strategy:
 #     max-parallel: 20
  #    fail-fast: false
   #   matrix:
    #    go: [1, 2, 3, 4]
     #   flag: [A, B, C, D, E]
#    env:
 #       NUM_JOBS: 20
  #      JOB: ${{ matrix.go }}

    steps:
      - uses: actions/checkout@v3

      - name: Docker Run
        run: docker run -d -p 4444:4444 --shm-size="2g" selenium/standalone-chrome

      - uses: actions/setup-python@v4
        with:
           python-version: '3.10'
      - run: |
           pip install selenium requests whisper
           python main.py
